// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4qQdgz-vVVJK4m_ykfs0H_RGLsJH7qTs',
    appId: '1:454387083035:web:9324c49cbfaf339b8795be',
    messagingSenderId: '454387083035',
    projectId: 'lingua-neural-kids-app',
    authDomain: 'lingua-neural-kids-app.firebaseapp.com',
    storageBucket: 'lingua-neural-kids-app.firebasestorage.app',
    measurementId: 'G-E2006B7B69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_sGRyZKYr-olb0zlO6nd_wME7T2v04JA',
    appId: '1:454387083035:android:ecba2b9f51b25e028795be',
    messagingSenderId: '454387083035',
    projectId: 'lingua-neural-kids-app',
    storageBucket: 'lingua-neural-kids-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfNgJDSQuKMw7DCeKb6pXkEGeQ3JBbLQU',
    appId: '1:454387083035:ios:8c91cb8dcb84da258795be',
    messagingSenderId: '454387083035',
    projectId: 'lingua-neural-kids-app',
    storageBucket: 'lingua-neural-kids-app.firebasestorage.app',
    iosBundleId: 'com.example.linguaNeuralKidsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfNgJDSQuKMw7DCeKb6pXkEGeQ3JBbLQU',
    appId: '1:454387083035:ios:8c91cb8dcb84da258795be',
    messagingSenderId: '454387083035',
    projectId: 'lingua-neural-kids-app',
    storageBucket: 'lingua-neural-kids-app.firebasestorage.app',
    iosBundleId: 'com.example.linguaNeuralKidsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4qQdgz-vVVJK4m_ykfs0H_RGLsJH7qTs',
    appId: '1:454387083035:web:610461ee899ef8c68795be',
    messagingSenderId: '454387083035',
    projectId: 'lingua-neural-kids-app',
    authDomain: 'lingua-neural-kids-app.firebaseapp.com',
    storageBucket: 'lingua-neural-kids-app.firebasestorage.app',
    measurementId: 'G-WRZJLK17CF',
  );
}
